[project]
name = "Handing"
version = "0.1.0"
description = "Control PC with your Hands"
requires-python = ">=3.10"

dependencies = [
    "mediapipe>=1.0"
]

[project.optional-dependencies]
dev = ["pytest", "nuitka", "psutil"]

[project.scripts]
handing = "handing.__main__:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"